# Generated by .github/workflows/release.yml in mrsmsn/issue. Do not edit by hand.
class Issue < Formula
  desc "Local-first issue-management CLI with a lazygit-style TUI (lazyissue)"
  homepage "https://github.com/mrsmsn/issue"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mrsmsn/issue/releases/download/v0.1.1/issue_0.1.1_darwin_arm64.tar.gz"
      sha256 "cd0ce9a6a340028f9fd0a54d3d7622d40abdd2c8831183e74ef1e1c6e49d9696"
    end
    on_intel do
      url "https://github.com/mrsmsn/issue/releases/download/v0.1.1/issue_0.1.1_darwin_amd64.tar.gz"
      sha256 "c26debd4765754d4fff8b05421142455710a15a3a4df548815b1d2599eca7821"
    end
  end

  def install
    bin.install "issue"
    bin.install "lazyissue"

    # Run the just-installed binary to emit completions; installed into
    # Homebrew's completion dirs (already on the user's fpath) — so
    # `issue <Tab>` works with no `source` line, like gh.
    generate_completions_from_executable(
      bin/"issue", "completions",
      base_name: "issue", shells: [:bash, :zsh, :fish]
    )
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/issue --version")
    assert_match version.to_s, shell_output("#{bin}/lazyissue --version")
  end
end
