# Generated by .github/workflows/release.yml in mrsmsn/issue. Do not edit by hand.
class Issue < Formula
  desc "Local-first issue-management CLI with a lazygit-style TUI (lazyissue)"
  homepage "https://github.com/mrsmsn/issue"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mrsmsn/issue/releases/download/v0.1.2/issue_0.1.2_darwin_arm64.tar.gz"
      sha256 "14f09244b08389f06741c6d45d6bb9dbf47da0dff23b70ec2c3998e885c79fcb"
    end
    on_intel do
      url "https://github.com/mrsmsn/issue/releases/download/v0.1.2/issue_0.1.2_darwin_amd64.tar.gz"
      sha256 "816548862b38d04cd4f42dc03ce6eca812e64566027e54100d2537ce42620510"
    end
  end

  def install
    bin.install "issue"
    bin.install "lazyissue"

    # Run the just-installed binary to emit completions; installed into
    # Homebrew's completion dirs (already on the user's fpath) — so
    # `issue <Tab>` works with no `source` line, like gh.
    generate_completions_from_executable(
      bin/"issue", "completions",
      base_name: "issue", shells: [:bash, :zsh, :fish]
    )
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/issue --version")
    assert_match version.to_s, shell_output("#{bin}/lazyissue --version")
  end
end
